# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 20:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Full Name', max_length=70)),
                ('date', models.CharField(default='Pick a date', max_length=25)),
                ('reservation', models.CharField(default='Reservation', max_length=70)),
                ('email', models.CharField(default='Email', max_length=70)),
                ('phone_num', models.CharField(default='Phone ', max_length=10)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 27, 20, 51, 16, 471172))),
            ],
        ),
    ]
