# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Full Name', max_length=70, validators=['Invalid'])),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date created')),
                ('reservation', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time created')),
                ('email', models.EmailField(default='Email', max_length=70)),
                ('phone_num', models.CharField(default='Phone ', max_length=10)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 23, 20, 31, 37, 706669))),
            ],
        ),
    ]
