# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 20:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 27, 20, 51, 25, 245790)),
        ),
    ]
