# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170330_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.datetime.now),
        ),
    ]
