# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_request_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.CharField(default='Email', max_length=70),
        ),
        migrations.AddField(
            model_name='request',
            name='phone_num',
            field=models.CharField(default='Phone ', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
