# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170406_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 19, 38, 47, 944276)),
        ),
    ]
