# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 23, 22, 58, 54, 119870, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
