# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170423_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.CharField(default='Pick a date', max_length=25),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.CharField(default='Email', max_length=70),
        ),
        migrations.AlterField(
            model_name='request',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=70),
        ),
        migrations.AlterField(
            model_name='request',
            name='reservation',
            field=models.CharField(default='Reservation', max_length=70),
        ),
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 23, 20, 40, 15, 925451)),
        ),
    ]
