# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.CharField(max_length=70),
        ),
    ]
