# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170330_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
