# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20170326_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='reservation',
        ),
    ]
