# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_request_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
